dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.js"
          - "**/*.jsx"
          - "**/*.ts"
          - "**/*.tsx"
